### ISSUE TITLE
Build Legal Compliance Screen

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/website-client-shop#23]
### Reason

Build the UI design

### Description

We should build the Legal Compliance Screen.

It should have 2 components in the main content section

the audit trail and the chart component to datasources and approved for.

Also, it should have a custom select component to fit in the third column. It should work as a filter to the content.

Image for reference: 
 
<img width="864" alt="Captura de Tela 2024-04-15 às 13 17 35" src="https://github.com/tiki/website-client-shop/assets/96149507/47c021e5-9b47-48eb-81c1-52e66f9387b6">

### Success Criteria

- [ ] The Legal Compliance Screen
- [x] #24 
- [x] #25 
- [x] #26

**Comment by ricardobrg** [comment]
done in #29
